import { useShallow } from 'zustand/react/shallow'
import { useTraceStore } from '../store/useTraceStore'

export function useAppStoreSelection() {
  return useTraceStore(
    useShallow((state) => ({
      nodes: state.nodes,
      nodeTree: state.nodeTree,
      noteRelations: state.noteRelations,
      activeNoteId: state.activeNoteId,
      activeView: state.activeView,
      pinnedNoteIds: state.pinnedNoteIds,
      recentConnectionIds: state.recentConnectionIds,
      selectedNodeId: state.selectedNodeId,
      viewMode: state.viewMode,
      loading: state.loading,
      vaultRequired: state.vaultRequired,
      saveStatus: state.saveStatus,
      error: state.error,
      graphData: state.graphData,
      traceDir: state.traceDir,
      traceConfigJson: state.traceConfigJson,
      customCss: state.customCss,
      customizationLoading: state.customizationLoading,
      customizationSaving: state.customizationSaving,
      ioWorking: state.ioWorking,
      ioMessage: state.ioMessage,
      markdownDbLoading: state.markdownDbLoading,
      markdownDbSnapshot: state.markdownDbSnapshot,
      activeVaultPath: state.activeVaultPath,
      commandSearchResults: state.commandSearchResults,
      commandSearchLoading: state.commandSearchLoading,
      editorWidth: state.editorWidth,
      isSidebarOpen: state.isSidebarOpen,
      isPropertiesPanelOpen: state.isPropertiesPanelOpen,
      isBacklinksPanelOpen: state.isBacklinksPanelOpen,
      uiModules: state.uiModules,
      draftNote: state.draftNote,
      draftRelatedNoteIds: state.draftRelatedNoteIds,
      isDirty: state.isDirty,
      initialize: state.initialize,
      selectVaultPath: state.selectVaultPath,
      loadVaultCustomization: state.loadVaultCustomization,
      saveVaultCustomization: state.saveVaultCustomization,
      importMarkdownFromDir: state.importMarkdownFromDir,
      exportCurrentNoteToMarkdown: state.exportCurrentNoteToMarkdown,
      exportVaultToMarkdown: state.exportVaultToMarkdown,
      refreshMarkdownDatabase: state.refreshMarkdownDatabase,
      updateMarkdownDatabaseProperty: state.updateMarkdownDatabaseProperty,
      runGlobalSearch: state.runGlobalSearch,
      clearGlobalSearch: state.clearGlobalSearch,
      selectNode: state.selectNode,
      setViewMode: state.setViewMode,
      createWorkspace: state.createWorkspace,
      createFolder: state.createFolder,
      createNewNote: state.createNewNote,
      createNoteFromTitle: state.createNoteFromTitle,
      deleteNodeById: state.deleteNodeById,
      renameNodeById: state.renameNodeById,
      changeNodeIconById: state.changeNodeIconById,
      moveNodeById: state.moveNodeById,
      setNoteTagsById: state.setNoteTagsById,
      beginNoteDraft: state.beginNoteDraft,
      discardDraft: state.discardDraft,
      commitDraftToDB: state.commitDraftToDB,
      addDraftRelation: state.addDraftRelation,
      removeDraftRelation: state.removeDraftRelation,
      openConnectModal: state.openConnectModal,
      pinNote: state.pinNote,
      setActiveView: state.setActiveView,
      setActiveNote: state.setActiveNote,
      queueNoteTitleSave: state.queueNoteTitleSave,
      queueSaveContent: state.queueSaveContent,
      saveNoteNow: state.saveNoteNow,
      hasPendingChanges: state.hasPendingChanges,
      toggleSidebar: state.toggleSidebar,
      togglePropertiesPanel: state.togglePropertiesPanel,
      toggleBacklinksPanel: state.toggleBacklinksPanel,
      updateUIModule: state.updateUIModule,
      setEditorWidth: state.setEditorWidth,
      unpinNote: state.unpinNote,
    })),
  )
}
